n=input('"Type something"')
print(type(n))
print(n.isalpha())
print(n.isalnum())
print(n.istitle())
print(n.islower())
print(n.isdecimal())
print(n.isnumeric())
print(n.isspace())
print(n.isascii())
print(n.isdigit())
