frase = str(input('Write any sentence:'))
frase = frase.strip()
maiuscula = frase.upper()
letraA = maiuscula.count('A')
posicao = maiuscula.find("A")
last_posicao = frase.rfind('A')
print('The letter A appears {} times in your sentence.'.format(letraA))
print('The first letter A is at position {}:'.format(posicao))
print('The last occurrence of the letter A {} is at position:'.format(last_posicao))
